fontsize = 13;
fontType = 'Times';

set(0,'Defaulttextinterpreter','latex',...
    'DefaultLegendInterpreter', 'latex',...
    'DefaultAxesTickLabelInterpreter', 'latex',...
    'DefaultTextFontSize', fontsize,...
    'DefaultAxesFontName', fontType,...
    'DefaultLegendFontSize', fontsize,...
    'DefaultLegendFontName', fontType,...
'DefaultAxesFontSize', fontsize,...
'DefaultLineLineWidth', 2,...
'DefaultLineMarkerSize', 6,...
'DefaultTextHorizontalAlignment', 'left')